FROM php:8.3-fpm

# Set working directory
WORKDIR /var/www

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cron \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    zip \
    jpegoptim optipng pngquant gifsicle \
    vim \
    unzip \
    git \
    curl \
    libonig-dev \
    libzip-dev \
    libgd-dev \
    supervisor \
    ffmpeg \
    sudo
# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl
RUN docker-php-ext-configure gd --with-external-gd
RUN docker-php-ext-install gd
RUN docker-php-ext-install opcache

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


# Create the log file to be able to run tail
RUN touch /var/log/cron.log
# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www
RUN echo "www  ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
RUN mkdir /var/run/supervisor
RUN chown www:www /var/run/supervisor
RUN chown -R www:www /var/log/supervisor

# Copy existing application directory permissions
RUN chown -R www:www /var/www

COPY ./docker/entrypoint.sh /entrypoint.sh
EXPOSE 9000
USER www
ENTRYPOINT [ "/entrypoint.sh" ]