services:
    app:
        build:
          context: .
          dockerfile: Dockerile.83 # <== change docker file here
        image: laravel-fpm
        volumes:
            - ./app:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - appnet
    webserver:
        image: nginx:alpine
        volumes:
            - ./app:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - appnet
        ports:
            - 8080:80

networks:
    appnet:
        driver: bridge
